### ISSUE TITLE
Content negotiation for detaljert innhold https://data.norge.no/organizations/

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/organization-catalogue#113]
Ser at det står BETA, men veldig bra at det nå er menneskevennlig visning av detaljert innhold for organisasjonene i FDK, f.eks.  https://data.norge.no/organizations/991825827. Savner maskinlesbart (RDF) innhold bak samme URI. 

Hittil har vi anbefalt i spesifikasjonene våre å bruke mønsteret https://organization-catalogue.fellesdatakatalog.digdir.no/organizations/991825827 som gir RDF men ikke menneskevennlig html-visning. Kunne vært veldig fint å "slå sammen" disse to.

**Comment by stigbd** [comment]
Vi implementerer dette i applikasjonen.  Applikasjonen veit om enhetsregistrer-url, så dermed er dette grei skuring.

Forøvrig: sjekk om ikkje #102  blir løyst av denne fiksen.

**Comment by jimjyang** [comment]
> Forøvrig: sjekk om ikkje #102 blir løyst av denne fiksen.

Ja, dette bør løse for #102 også, slik jeg forstår det.
