### ISSUE TITLE
feature: Legg til støtte for organisasjonsidentifkator

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/organization-catalogue#71]
Legg til egenskapen https://data.norge.no/specification/dcat-ap-no/#Akt%C3%B8r-organisasjonsidentifikator

**Comment by shenluna** [comment]
Testet i staging og verifisert i prod
![image](https://user-images.githubusercontent.com/73637969/106882940-9ba5b300-66df-11eb-8690-002b23f4a431.png)
