### ISSUE TITLE
Månedlig oppdatering av cache-data fra enhetsregisteret

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/organization-catalogue#91]

**Comment by lillelars** [comment]
Ferdigstilt. Lukker saken.

**Comment by lillelars** [comment]
må verifiseres i prod. Ser ut til at den beholder noe av gammel informasjon?
ref: https://organization-catalogue.fellesdatakatalog.digdir.no/organizations/974760665

Se preflabel her vs name:

m/ <name>STATSFORVALTAREN I VESTLAND</name>
og <nb>FYLKESMANNEN I VESTLAND</nb>

**Comment by lillelars** [comment]
Håndterer ny oppgave i:
https://github.com/Informasjonsforvaltning/organization-catalogue/issues/95
