### ISSUE TITLE
Håndtering av ulik preflabel og name

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/organization-catalogue#95]
Dersom preflabel != name etter månedlig opppdatering
( ref: https://github.com/informasjonsforvaltning/organization-catalogue/issues/91 )
bør det sendes en notification angående dette / eller en loggføring på det - slik at vi kan plukke opp og i minste fall manuelt håndtere dersom enhetsregisteret har endret navn på en organisasjon.

**Comment by shenluna** [comment]
Logikken som er blitt lagt til:

- hvis den ikke klarte å laste ned et navn fra brreg så endrer den ikke prefLabel
- hvis prefLabel ikke har data så legger den til ny
- hvis organisasjonen har nytt navn i brreg i forhold til hva som er lagret i organization catalogue så oppdaterer den prefLabel
- ellers endrer den ikke prefLabel

**Comment by shenluna** [comment]
Testet i demo
![image](https://user-images.githubusercontent.com/73637969/110446540-97dec500-80bf-11eb-972c-667bc24038e3.png)
